development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: staging_credit_test
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock

test:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: test_credit_test
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
